### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by pschulz** [mmattozzi/url-encode#9]
[Enter steps to reproduce below:]
1. Follow the steps at described in Commands...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.9.5
**Thrown From**: [url-encode](https://github.com/mmattozzi/url-encode) package, v0.5.0
### Stack Trace

Uncaught URIError: URI malformed

```
At /Users/patrick/.atom/packages/url-encode/lib/url-encode.coffee:25

URIError: URI malformed
    at decodeURIComponent (native)
    at Object.module.exports.transfromSel (/Users/patrick/.atom/packages/url-encode/lib/url-encode.coffee:25:40)
    at atom-workspace.atom.commands.add.url-encode:decode (/Users/patrick/.atom/packages/url-encode/lib/url-encode.coffee:12:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:09.6.0 core:paste (atom-text-editor.editor.is-focused)
     -0:06.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:04.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 url-encode:decode (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "compare-files",
      "log-console",
      "github-issues"
    ],
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ascii-codes, v0.3.3
emmet, v2.3.14
hex, v0.6.2
html-entities, v0.4.0
language-puppet, v0.15.0
linter, v1.10.0
linter-php, v1.0.5
linter-xmllint, v0.0.7
node-debugger, v1.1.9
php-getters-setters, v0.5.5
project-manager, v2.6.5
url-encode, v0.5.0
view-tail-large-files, v0.2.1

# Dev
No dev packages
```

**Comment by surfer190** [comment]
Yip, I also get this one.

Maybe a better choice would be to use (escape-utils)[https://atom.io/packages/escape-utils] for now.
